from django import forms
from .models import DhanCredentials, StrategySettings

class DhanCredentialsForm(forms.ModelForm):
    """
    Form to input Dhan Client ID and display the Access Token status.
    This form also includes the temporary 'auth_code' field required to 
    exchange for a live Access Token via the Dhan API call in views.py.
    """
    
    # NEW FIELD: Field for Authorization Code input (not saved to the model)
    auth_code = forms.CharField(
        max_length=255, 
        required=False, 
        label="Authorization Code (For New Token)",
        help_text="Paste the code obtained from Dhan's login redirect here before clicking 'Generate Token'."
    )

    class Meta:
        model = DhanCredentials
        # Fields must match existing Model fields
        fields = ['client_id', 'access_token'] 
        widgets = {
            # Mark access_token as read-only since it is generated by the API call, not manual input.
            'access_token': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'bg-gray-100 cursor-not-allowed', 'placeholder': 'Generated upon successful authentication.'}),
        }

class StrategySettingsForm(forms.ModelForm):
    """Form to update the main strategy settings."""
    class Meta:
        model = StrategySettings
        fields = [
            # Master Controls
            'name', 
            'is_enabled', 
            'manual_override',
            
            # Limits
            'max_trades_per_stock', 
            'max_total_trades',
            
            # Risk & Filters
            'per_trade_sl_amount', 
            'entry_offset_pct', 
            'stop_offset_pct', 
            'max_candle_pct',
            
            # Time & P&L Exits
            'start_time', 
            'end_time', 
            'pnl_exit_enabled',
            'pnl_profit_target',
            'pnl_stop_loss',
        ]

        # Use TextInput for time fields to ensure proper display and editing
        widgets = {
            'start_time': forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
            'end_time': forms.TimeInput(format='%H:%M', attrs={'type': 'time'}),
        }