from django import forms
from .models import DhanCredentials, StrategySettings

class DhanCredentialsForm(forms.ModelForm):
    """
    Form to input Dhan Client ID and display the Access Token status.
    The 'access_token' field exists in the model and form but is usually
    managed by the 'Generate Token' button, not manual entry.
    """
    class Meta:
        model = DhanCredentials
        # Fields must match existing Model fields
        fields = ['client_id', 'access_token']
        widgets = {
            # Hide the token field on the dashboard as it's generated by the button
            'access_token': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'bg-gray-100 cursor-not-allowed'}),
        }

class StrategySettingsForm(forms.ModelForm):
    """Form to update the main strategy settings."""
    class Meta:
        model = StrategySettings
        fields = [
            'name',
            'is_enabled',
            'manual_override',
            'max_trades_per_stock',
            'max_total_trades',
            'per_trade_sl_amount',
            'entry_offset_pct',
            'stop_offset_pct',
            'max_candle_pct',
            'start_time',
            'end_time',
            'pnl_exit_enabled',
            'pnl_profit_target',
            'pnl_stop_loss',
        ]