# Generated by Django 5.0.14 on 2025-11-27 18:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DhanCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Dhan Client ID"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Current Access Token",
                    ),
                ),
                ("token_generation_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Dhan Credentials",
            },
        ),
        migrations.CreateModel(
            name="StrategySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[("CASH_ALGO_1", "Cash Breakout Strategy")],
                        default="CASH_ALGO_1",
                        max_length=50,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enable Trading Logic (Master Switch)",
                    ),
                ),
                (
                    "max_trades_per_stock",
                    models.IntegerField(
                        default=2, verbose_name="Max Closed Trades per Symbol (Daily)"
                    ),
                ),
                (
                    "max_total_trades",
                    models.IntegerField(
                        default=10, verbose_name="Max Total Trades (Daily)"
                    ),
                ),
                (
                    "entry_offset_pct",
                    models.FloatField(
                        default=0.0001, verbose_name="Entry Buffer % (above High)"
                    ),
                ),
                (
                    "stop_offset_pct",
                    models.FloatField(
                        default=0.0002, verbose_name="SL Buffer % (below Low)"
                    ),
                ),
                (
                    "max_candle_pct",
                    models.FloatField(
                        default=0.007, verbose_name="Max Candle Size % Filter"
                    ),
                ),
                (
                    "per_trade_sl_amount",
                    models.FloatField(
                        default=2000.0, verbose_name="Max Rupee Risk per Trade"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(9, 20),
                        verbose_name="Strategy Start Time (IST)",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=datetime.time(15, 0),
                        verbose_name="Strategy End Time (IST - Force Square Off)",
                    ),
                ),
                (
                    "pnl_exit_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Enable Daily P&L Limits"
                    ),
                ),
                (
                    "pnl_profit_target",
                    models.FloatField(
                        default=5000.0, verbose_name="Daily Profit Target (₹)"
                    ),
                ),
                (
                    "pnl_stop_loss",
                    models.FloatField(
                        default=2500.0, verbose_name="Daily Stop Loss Limit (₹)"
                    ),
                ),
                (
                    "manual_override",
                    models.BooleanField(
                        default=False,
                        verbose_name="Manual Trade Control Override (Disable Algo Entries)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Strategy Settings",
            },
        ),
        migrations.CreateModel(
            name="CashBreakoutTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("security_id", models.CharField(max_length=20)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_ENTRY", "Pending Entry Order"),
                            ("OPEN", "Open Position"),
                            ("PENDING_EXIT", "Pending Exit Order"),
                            ("CLOSED", "Closed/Squared Off"),
                            ("EXPIRED", "Pending Entry Expired (6 min/SL)"),
                            ("FAILED_ENTRY", "Entry Order Failed/Rejected"),
                        ],
                        default="PENDING_ENTRY",
                        max_length=20,
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prev_day_high", models.FloatField(blank=True, null=True)),
                (
                    "entry_level",
                    models.FloatField(verbose_name="Target Entry Price (Trigger)"),
                ),
                ("stop_level", models.FloatField(verbose_name="Stop Loss Price")),
                ("target_level", models.FloatField(verbose_name="Target Price (2.5R)")),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                (
                    "entry_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exit_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("candle_ts", models.DateTimeField(verbose_name="Candle Signal Time")),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pnl", models.FloatField(default=0.0, verbose_name="Realized PnL")),
                ("candle_high", models.FloatField(blank=True, null=True)),
                ("candle_low", models.FloatField(blank=True, null=True)),
                ("volume_price", models.FloatField(blank=True, null=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.strategysettings",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cash Breakout Trades",
            },
        ),
    ]
